title: Service
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: banner_image
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Banner Image'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: banner_title
            field:
              input_type: text
              default: 'Spa Service'
              antlers: false
              type: text
              display: 'Banner Title'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: short_description
            field:
              default: 'Microdermabrasion exfoliates and resurfaces the skin, reducing fine lines, wrinkles, and hyperpigmentation. Gentle yet effective, it reveals smoother, brighter, and more radiant complexion instantly.'
              antlers: false
              type: textarea
              display: 'Short Description'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: heading
            field:
              input_type: text
              default: 'Spa Service'
              antlers: false
              type: text
              display: Heading
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: long_description
            field:
              buttons:
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - image
                - table
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: 'Long Description'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: image_1
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Image 1'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: image_2
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Image 2'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: youtube_video_link
            field:
              input_type: text
              default: 'https://youtu.be/xRwRv8GJXtM?si=n97qSK-sFDMeSowJ'
              antlers: false
              type: text
              display: 'Youtube Video Link'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: button_text
            field:
              input_type: text
              default: 'Order Now'
              antlers: false
              type: text
              display: 'Button Text'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: author
            field:
              type: users
              display: Author
              default: current
              localizable: true
              max_items: 1
          -
            handle: template
            field:
              type: template
              display: Template
              localizable: true
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
  seo:
    display: SEO
    sections:
      -
        display: SEO
        fields:
          -
            handle: seo_title
            field:
              input_type: text
              placeholder: 'Spa Service'
              antlers: false
              type: text
              display: 'Seo Title'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: seo_keywords
            field:
              default: 'Spa Service'
              antlers: false
              type: textarea
              display: 'Seo Keywords'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: seo_description
            field:
              default: 'SEO Description'
              antlers: false
              type: textarea
              display: 'Seo Description'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  additonal_content:
    display: 'Additonal Content'
    sections:
      -
        display: 'Block Types'
        fields:
          -
            handle: content
            field: block_types.content
